#!/usr/bin/env python3
import argparse
import json
import sqlite3
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Analyze remote_perf_snapshot payloads stored by webhook_vps.py"
    )
    parser.add_argument(
        "--db",
        default="test/local-webhook.sqlite3",
        help="SQLite DB generated by webhook_vps.py",
    )
    parser.add_argument(
        "--results",
        default=None,
        help="Optional k6 results JSON to print p99/score alongside telemetry",
    )
    parser.add_argument(
        "--snapshot-id",
        type=int,
        default=None,
        help="Specific webhook request id to analyze",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=200,
        help="How many latest webhook rows to scan for a full snapshot",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=12,
        help="How many stages/hotspots to print",
    )
    return parser.parse_args()


def load_snapshot(db_path, snapshot_id=None, limit=200):
    con = sqlite3.connect(db_path)
    if snapshot_id is not None:
        rows = con.execute(
            "select id, received_at, body from requests where id = ?", (snapshot_id,)
        ).fetchall()
    else:
        rows = con.execute(
            "select id, received_at, body from requests order by id desc limit ?", (limit,)
        ).fetchall()

    fallback = None
    for row_id, received_at, body in rows:
        try:
            payload = json.loads(body)
        except Exception:
            continue
        if payload.get("event") not in {
            "remote_perf_snapshot",
            "remote_perf_final_snapshot",
        }:
            continue
        if fallback is None:
            fallback = (row_id, received_at, payload)
        if len(payload.get("relayed", [])) >= 2:
            return row_id, received_at, payload

    if fallback:
        return fallback
    raise SystemExit("No remote_perf_snapshot found in webhook database")


def unwrap_process(wrapper):
    return wrapper.get("local", wrapper)


def merge_stage(target, stage):
    if not stage.get("count"):
        return
    name = stage["stage"]
    item = target.setdefault(
        name,
        {
            "count": 0,
            "total_us": 0,
            "p50_us": 0,
            "p95_us": 0,
            "p99_us": 0,
            "p999_us": 0,
            "max_us": 0,
        },
    )
    item["count"] += stage["count"]
    item["total_us"] += stage["total_us"]
    item["p50_us"] = max(item["p50_us"], stage["p50_us"])
    item["p95_us"] = max(item["p95_us"], stage["p95_us"])
    item["p99_us"] = max(item["p99_us"], stage["p99_us"])
    item["p999_us"] = max(item["p999_us"], stage["p999_us"])
    item["max_us"] = max(item["max_us"], stage["max_us"])


def avg_us(item):
    return item["total_us"] / item["count"] if item["count"] else 0.0


def pct(part, total):
    return (part * 100 / total) if total else 0.0


def print_results(path):
    if not path:
        return
    data = json.loads(Path(path).read_text())
    scoring = data.get("scoring", {})
    print("K6")
    print(f"  p99: {data.get('p99')}")
    print(f"  score: {scoring.get('final_score')}")
    print(f"  failure_rate: {scoring.get('failure_rate')}")
    breakdown = scoring.get("breakdown", {})
    print(f"  http_errors: {breakdown.get('http_errors')}")
    print()


def analyze(snapshot, top):
    local = snapshot.get("local", {})
    processes = [unwrap_process(item) for item in snapshot.get("relayed", [])]
    if local:
        role = local.get("role")
        if role and role != "lb":
            processes.append(local)

    cumulative = {}
    window = {}
    total_requests = 0
    total_hits = 0
    total_misses = 0
    total_bytes_in = 0
    total_bytes_out = 0

    print("Snapshot")
    print(f"  event: {snapshot.get('event')}")
    print(f"  timestamp: {snapshot.get('timestamp')}")
    print(f"  aggregator: {snapshot.get('aggregator')}")
    print(f"  shutdown: {snapshot.get('shutdown', False)}")
    print()

    if local:
        print("Load Balancer")
        print(f"  lb counters: {json.dumps(local.get('lb', {}), ensure_ascii=False)}")
        print(f"  cpu_percent: {local.get('cpu', {}).get('percent')}")
        print(f"  rss_mb: {local.get('memory', {}).get('rss_mb')}")
        print()

    print("Processes")
    for proc in processes:
        role = proc.get("role", "unknown")
        requests = proc.get("requests", 0)
        total_requests += requests
        total_hits += proc.get("cache_hits", 0)
        total_misses += proc.get("cache_misses", 0)
        total_bytes_in += proc.get("bytes_received", 0)
        total_bytes_out += proc.get("bytes_sent", 0)
        for stage in proc.get("stages_cumulative", []):
            merge_stage(cumulative, stage)
        for stage in proc.get("stages_window", []):
            merge_stage(window, stage)
        print(
            f"  {role}: requests={requests} rps={proc.get('rps'):.2f} "
            f"cpu={proc.get('cpu', {}).get('percent'):.2f}% "
            f"rss={proc.get('memory', {}).get('rss_mb'):.2f}MB"
        )
        print(f"    socket={json.dumps(proc.get('socket', {}), ensure_ascii=False)}")
    print()

    print("Totals")
    print(f"  requests: {total_requests}")
    print(f"  cache_hit_rate: {pct(total_hits, total_hits + total_misses):.2f}%")
    if total_requests:
        print(f"  bytes_received_per_request: {total_bytes_in / total_requests:.1f}")
        print(f"  bytes_sent_per_request: {total_bytes_out / total_requests:.1f}")
    print()

    print_stage_table("Cumulative Stage Ranking", cumulative, top)
    print_stage_table("Window Stage Ranking", window, top)
    print_recommendations(cumulative, window)


def print_stage_table(title, stages, top):
    print(title)
    print("  stage                         avg_us p50 p95 p99 p999 max count total_us")
    for name, item in sorted(
        stages.items(), key=lambda entry: entry[1]["total_us"], reverse=True
    )[:top]:
        print(
            f"  {name:<28} "
            f"{avg_us(item):>6.2f} "
            f"{item['p50_us']:>3} "
            f"{item['p95_us']:>3} "
            f"{item['p99_us']:>3} "
            f"{item['p999_us']:>4} "
            f"{item['max_us']:>4} "
            f"{item['count']:>6} "
            f"{item['total_us']:>8}"
        )
    print()


def print_recommendations(cumulative, window):
    source = window or cumulative
    request = source.get("request_total", {})
    write = source.get("write_complete", {})
    recv = source.get("socket_recv", {})
    parse = source.get("parse_json", {})
    decision = source.get("decision_tree", {})

    total = request.get("total_us", 0)
    print("Interpretation")
    if write:
        print(
            f"  socket write: {pct(write['total_us'], total):.1f}% of measured request time "
            f"(avg {avg_us(write):.2f}us, p99 {write['p99_us']}us)"
        )
    if recv:
        print(
            f"  socket recv: {pct(recv['total_us'], total):.1f}% "
            f"(avg {avg_us(recv):.2f}us, p99 {recv['p99_us']}us)"
        )
    if parse:
        print(
            f"  json parse: {pct(parse['total_us'], total):.1f}% "
            f"(avg {avg_us(parse):.2f}us, p99 {parse['p99_us']}us)"
        )
    if decision:
        print(
            f"  decision tree: {pct(decision['total_us'], total):.1f}% "
            f"(avg {avg_us(decision):.2f}us, p99 {decision['p99_us']}us)"
        )
    print()


def main():
    args = parse_args()
    row_id, received_at, snapshot = load_snapshot(
        args.db, snapshot_id=args.snapshot_id, limit=args.limit
    )
    print_results(args.results)
    print(f"Webhook row: id={row_id} received_at={received_at}")
    print()
    analyze(snapshot, args.top)


if __name__ == "__main__":
    main()
